version: '3.3'

services:
  web:
    build: . # Busca el dockerfile en .
    ports: 
      - "8000:8000" # externo:interno
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    
  db:
    image: postgres:15
    volumes: 
      - ../data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=db_django_docker
    ports:
      - "5432:5432"

volumes:
  pg_data: